/*
 * This file was automatically generated by EvoSuite
 * Thu Dec 02 01:46:35 GMT 2021
 */

package com.mycompany.app;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.mycompany.app.Cal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Cal_ESTest extends Cal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        Cal.cal((-136), 952, 952, 1697, (-3000));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -136
         //
         verifyException("com.mycompany.app.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Cal.cal(388, 0, 0, 0, (-1516));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 388
         //
         verifyException("com.mycompany.app.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = Cal.cal((-3437), 0, (-3437), (-3437), 3);
      assertEquals((-3437), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = Cal.cal(1691, 1691, 1691, (-2220), 1691);
      assertEquals((-3911), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = Cal.cal(0, (-136), (-136), 0, 0);
      assertEquals(136, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      int int0 = Cal.cal(0, 906, (-1643), 263, 263);
      assertEquals((-643), int0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      // Undeclared exception!
      try { 
        Cal.cal(0, (-1586), 1267, 1063, 500);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 13
         //
         verifyException("com.mycompany.app.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try { 
        Cal.cal(2449, 1, 0, 0, 12);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2449
         //
         verifyException("com.mycompany.app.Cal", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      int int0 = Cal.cal(0, 0, (-767), 0, (-3091));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Cal cal0 = new Cal();
  }
}
